name: Configure Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Cypress Fixture
        run: |
          mkdir -p cypress/fixtures
          echo '{"email":"${{ secrets.CYPRESS_TEST_EMAIL }}","password":"${{ secrets.CYPRESS_TEST_PASSWORD }}"}' > cypress/fixtures/loginCredentials.json

      # Install npm dependencies, cache them correctly
      # and run only Configure folder tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: "cypress/e2e/Configure/*.cy.ts"
        continue-on-error: true  # Add this to continue even if tests fail

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()  # Always upload videos
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: warn